Repository goorm-ticker/ticker-backend, pull requests merged in 2025-02, with the labels that each got.

#10 Feature/#2 예약 알림 기능 구현
  src/main/java/com/goorm/ticker/notification/dto/NotificationRequest.java
  src/main/java/com/goorm/ticker/notification/dto/NotificationResponse.java
  src/main/java/com/goorm/ticker/notification/entity/Notification.java
  src/main/java/com/goorm/ticker/notification/entity/NotificationType.java
Labels: ✨ Feature

#12 Feature/#3 예약 생성/상태 갱신 로직 구현
  src/main/java/com/goorm/ticker/common/exception/ErrorCode.java
  src/main/java/com/goorm/ticker/reservation/Entity/Reservation.java
  src/main/java/com/goorm/ticker/reservation/Entity/ReservationStatus.java
  src/main/java/com/goorm/ticker/reservation/controller/ReservationController.java
  src/main/java/com/goorm/ticker/reservation/dto/request/ReservationCreateRequest.java
  src/main/java/com/goorm/ticker/reservation/dto/response/ReservationCreateResponse.java
  src/main/java/com/goorm/ticker/reservation/repository/ReservationRepository.java
  src/main/java/com/goorm/ticker/reservation/service/ReservationService.java
  src/main/java/com/goorm/ticker/restaurant/entity/ReservationSlot.java
  src/main/java/com/goorm/ticker/restaurant/entity/Restaurant.java
  src/main/java/com/goorm/ticker/restaurant/repository/ReservationSlotRepository.java
  src/main/java/com/goorm/ticker/restaurant/repository/RestaurantRepository.java
  src/test/java/com/goorm/ticker/fixture/ReservationFixture.java
  src/test/java/com/goorm/ticker/fixture/ReservationSlotFixture.java
  src/test/java/com/goorm/ticker/fixture/RestaurantFixture.java
  src/test/java/com/goorm/ticker/fixture/UserFixture.java
  src/test/java/com/goorm/ticker/reservation/controller/ReservationControllerTest.java
  src/test/java/com/goorm/ticker/reservation/service/ReservationServiceTest.java
Labels: ✅ Test, ✨ Feature

#16 Feature/#2 예약 알림 기능 구현
  src/main/java/com/goorm/ticker/notification/controller/NotificationController.java
  src/main/java/com/goorm/ticker/notification/entity/Notification.java
  src/main/java/com/goorm/ticker/notification/repository/NotificationRepository.java
  src/main/java/com/goorm/ticker/notification/service/NotificationService.java
  src/test/java/com/goorm/ticker/notification/service/NotificationServiceTest.java
Labels: ✅ Test, ✨ Feature

#17 Feature/#4 대기열 기능 구현
  src/main/java/com/goorm/ticker/common/exception/ErrorCode.java
  src/main/java/com/goorm/ticker/waitlist/controller/WaitListController.java
  src/main/java/com/goorm/ticker/waitlist/dto/WaitListRequestDto.java
  src/main/java/com/goorm/ticker/waitlist/dto/WaitListResponseDto.java
  src/main/java/com/goorm/ticker/waitlist/entity/Status.java
  src/main/java/com/goorm/ticker/waitlist/entity/WaitList.java
  src/main/java/com/goorm/ticker/waitlist/repository/WaitListRepository.java
  src/main/java/com/goorm/ticker/waitlist/service/CancelWaitingService.java
  src/main/java/com/goorm/ticker/waitlist/service/CompleteWaitingService.java
  src/main/java/com/goorm/ticker/waitlist/service/RegisterWaitingService.java
  src/main/java/com/goorm/ticker/waitlist/service/RestaurantWaitingService.java
  src/main/java/com/goorm/ticker/waitlist/service/UserWaitingPositionService.java
  src/main/java/com/goorm/ticker/waitlist/service/WaitingListService.java
  src/test/java/com/goorm/ticker/waitlist/controller/WaitListControllerTest.java
  src/test/java/com/goorm/ticker/waitlist/service/CancelWaitingServiceTest.java
  src/test/java/com/goorm/ticker/waitlist/service/CompleteWaitingServiceTest.java
  src/test/java/com/goorm/ticker/waitlist/service/RegisterWaitingServiceTest.java
  src/test/java/com/goorm/ticker/waitlist/service/UserWaitingPositionServiceTest.java
Labels: ✅ Test, ✨ Feature

#21 Feature/#20 식당 총 대기인원 조회 구현
  src/main/java/com/goorm/ticker/waitlist/controller/WaitListController.java
  src/main/java/com/goorm/ticker/waitlist/repository/WaitListRepository.java
  src/main/java/com/goorm/ticker/waitlist/service/WaitingPositionService.java
  src/test/java/com/goorm/ticker/waitlist/controller/WaitListControllerTest.java
  src/test/java/com/goorm/ticker/waitlist/service/WaitingPositionServiceTest.java
Labels: ✨ Feature, 🔨 Refactor

#15 feat: 실시간 대기열 지도 sse 추가
  src/main/java/com/goorm/ticker/map/controller/MapController.java
  src/main/java/com/goorm/ticker/map/dto/MapUpdateDto.java
  src/main/java/com/goorm/ticker/map/service/MapService.java
  src/main/java/com/goorm/ticker/map/util/RestaurantEmitter.java
  src/main/java/com/goorm/ticker/restaurant/entity/Restaurant.java
  src/main/java/com/goorm/ticker/restaurant/repository/RestaurantRepository.java
  src/main/java/com/goorm/ticker/waitlist/repository/WaitListRepository.java
  src/main/java/com/goorm/ticker/waitlist/service/CancelWaitingService.java
  src/main/java/com/goorm/ticker/waitlist/service/CompleteWaitingService.java
  src/main/java/com/goorm/ticker/waitlist/service/RegisterWaitingService.java
  src/main/resources/application.yml
  src/test/java/com/goorm/ticker/fixture/RestaurantFixture.java
  src/test/java/com/goorm/ticker/waitlist/controller/WaitListControllerTest.java
  src/test/java/com/goorm/ticker/waitlist/service/CancelWaitingServiceTest.java
  src/test/java/com/goorm/ticker/waitlist/service/CompleteWaitingServiceTest.java
  src/test/java/com/goorm/ticker/waitlist/service/RegisterWaitingServiceTest.java
Labels: ✨ Feature

#26 Feature/#23 대기열 예상시간 추가
  src/main/java/com/goorm/ticker/waitlist/controller/WaitListController.java
  src/main/java/com/goorm/ticker/waitlist/dto/WaitingInfoResponseDto.java
  src/main/java/com/goorm/ticker/waitlist/service/WaitingPositionService.java
  src/test/java/com/goorm/ticker/waitlist/service/WaitingPositionServiceTest.java
Labels: ✨ Feature

#34 refactor: SSE 연결로직 수정
  src/main/java/com/goorm/ticker/map/controller/MapController.java
  src/main/java/com/goorm/ticker/map/dto/MapUpdateDto.java
  src/main/java/com/goorm/ticker/map/service/MapService.java
  src/main/java/com/goorm/ticker/map/util/RestaurantEmitter.java
  src/main/java/com/goorm/ticker/waitlist/controller/WaitListController.java
  src/main/java/com/goorm/ticker/waitlist/service/WaitingPositionService.java
  src/test/java/com/goorm/ticker/waitlist/controller/WaitListControllerTest.java
  src/test/java/com/goorm/ticker/waitlist/service/WaitingPositionServiceTest.java
Labels: 🔨 Refactor

#39 refactor: 대기열 코드 리팩토링
  src/main/java/com/goorm/ticker/common/service/SessionService.java
  src/main/java/com/goorm/ticker/waitlist/controller/WaitListController.java
  src/main/java/com/goorm/ticker/waitlist/service/CancelWaitingService.java
  src/main/java/com/goorm/ticker/waitlist/service/CompleteWaitingService.java
  src/main/java/com/goorm/ticker/waitlist/service/RegisterWaitingService.java
  src/main/java/com/goorm/ticker/waitlist/service/RestaurantWaitingService.java
  src/main/java/com/goorm/ticker/waitlist/service/WaitListService.java
  src/main/java/com/goorm/ticker/waitlist/service/WaitListServiceImpl.java
  src/main/java/com/goorm/ticker/waitlist/service/WaitingListService.java
  src/main/java/com/goorm/ticker/waitlist/service/WaitingPositionService.java
  src/test/java/com/goorm/ticker/waitlist/service/CancelWaitingServiceTest.java
  src/test/java/com/goorm/ticker/waitlist/service/CompleteWaitingServiceTest.java
  src/test/java/com/goorm/ticker/waitlist/service/RegisterWaitingServiceTest.java
  src/test/java/com/goorm/ticker/waitlist/service/WaitingPositionServiceTest.java
Labels: ✅ Test, ✨ Feature, 🔨 Refactor

#40 Feature/#2 알림 기능
  src/main/java/com/goorm/ticker/notification/dto/NotificationRequest.java
  src/main/java/com/goorm/ticker/notification/entity/Notification.java
  src/main/java/com/goorm/ticker/notification/publisher/ReservationStatusPublisher.java
  src/main/java/com/goorm/ticker/notification/service/NotificationService.java
  src/main/java/com/goorm/ticker/notification/subscriber/ReservationStatusSubscriber.java
  src/main/java/com/goorm/ticker/reservation/Entity/Reservation.java
  src/main/java/com/goorm/ticker/reservation/ReservationScheduler.java
  src/main/java/com/goorm/ticker/reservation/repository/ReservationRepository.java
  src/main/java/com/goorm/ticker/reservation/service/ReservationService.java
  src/test/java/com/goorm/ticker/notification/service/NotificationServiceTest.java
  src/test/java/com/goorm/ticker/reservation/integration/ReservationConcurrencyTest.java
  src/test/java/com/goorm/ticker/reservation/service/ReservationServiceTest.java
Labels: ✅ Test, ✨ Feature, 🔨 Refactor

#42 refactor: 업데이트 알림 로직 쿼리 단일화
  src/main/java/com/goorm/ticker/map/service/MapService.java
  src/main/java/com/goorm/ticker/waitlist/repository/WaitListRepository.java
Labels: 🔨 Refactor

#44 Feature/#2 알림 기능
  src/main/java/com/goorm/ticker/TickerApplication.java
  src/main/java/com/goorm/ticker/map/service/MapService.java
  src/main/java/com/goorm/ticker/notification/scheduler/ReservationScheduler.java
  src/main/java/com/goorm/ticker/notification/scheduler/WaitingListScheduler.java
  src/main/java/com/goorm/ticker/notification/service/NotificationService.java
  src/main/java/com/goorm/ticker/notification/subscriber/ReservationStatusSubscriber.java
  src/main/java/com/goorm/ticker/reservation/service/ReservationService.java
  src/main/java/com/goorm/ticker/waitlist/repository/WaitListRepository.java
  src/main/java/com/goorm/ticker/waitlist/service/CompleteWaitingService.java
  src/test/java/com/goorm/ticker/notification/service/EntryPossibleNotificationTest.java
  src/test/java/com/goorm/ticker/waitlist/service/CompleteWaitingServiceTest.java
Labels: ✅ Test, ✨ Feature, 🔨 Refactor

#46 Refacotor: 알림 API 리팩토링
  src/main/java/com/goorm/ticker/notification/controller/NotificationController.java
  src/main/java/com/goorm/ticker/notification/service/NotificationService.java
Labels: 🔨 Refactor
